#!/bin/sh

# script/bootstrap: Install project dependencies and setup the local environment.

set -e

cat <<"EOF"
* * * * * * * * * * * * * * * * * * * * * *
*         Level Bootstrap Script          *
* * * * * * * * * * * * * * * * * * * * * *
EOF

# Verify that elixir is installed
command -v mix >/dev/null 2>&1 || {
  echo >&2 "Whoops! You need to install Elixir first.";
  echo >&2 "Follow the instructions here, then try again:";
  echo >&2 "https://elixir-lang.org/install.html";
  exit 1;
}

# Verify that yarn is installed
command -v yarn >/dev/null 2>&1 || {
  echo >&2 "Whoops! You need to install Yarn first.";
  echo >&2 "Follow the instructions here, then try again:";
  echo >&2 "https://yarnpkg.com/en/docs/install";
  exit 1;
}

# Verify that Postgres is installed
command -v psql >/dev/null 2>&1 || {
  echo >&2 "Whoops! You need to install Postgres first.";
  echo >&2 "We recommend Postgres.app for Mac:";
  echo >&2 "https://postgresapp.com";
  exit 1;
}

# Copy development secrets config
cp -n config/secret_template.exs config/dev.secret.exs

# Install dependencies
echo "==> Installing Elixir dependencies"
mix deps.get

# Install node dependencies
echo "==> Installing node.js dependencies"
cd assets && yarn
npm install -g elm-format

# Setup the local database
echo "==> Creating the development database"
cd ../ && mix ecto.create && mix ecto.load

# Seed the database
echo "==> Seeding the database"
mix run priv/repo/seeds.exs
