#!/bin/sh

set -e

cat <<"EOF"

+ + + + + + + + + + + + + + + + + + + + +
+     ____       _     _                +
+    |  _ \     (_)   | |               +
+    | |_) |_ __ _  __| | __ _  ___     +
+    |  _ <| '__| |/ _` |/ _` |/ _ \    +
+    | |_) | |  | | (_| | (_| |  __/    +
+    |____/|_|  |_|\__,_|\__, |\___|    +
+                         __/ |         +
+                        |___/          +
+ + + + + + + + + + + + + + + + + + + + +

            Bootstrap Script

EOF

# Verify that elixir is installed
command -v mix >/dev/null 2>&1 || {
  echo >&2 "Whoops! You need to install Elixir first.";
  echo >&2 "Follow the instructions here, then try again:";
  echo >&2 "https://elixir-lang.org/install.html";
  exit 1;
}

# Verify that yarn is installed
command -v yarn >/dev/null 2>&1 || {
  echo >&2 "Whoops! You need to install Yarn first.";
  echo >&2 "Follow the instructions here, then try again:";
  echo >&2 "https://yarnpkg.com/en/docs/install";
  exit 1;
}

# Verify that Postgres is installed
command -v psql >/dev/null 2>&1 || {
  echo >&2 "Whoops! You need to install Postgres first.";
  echo >&2 "We recommend Postgres.app for Mac:";
  echo >&2 "https://postgresapp.com";
  exit 1;
}

# Install dependencies
echo "* Installing Elixir dependencies"
mix deps.get

# Install node dependencies
echo "* Installing node.js dependencies"
cd assets && yarn
npm install -g rtfeldman/node-test-runner elm-format

# Setup the local database
echo "* Creating the development database"
cd ../ && mix ecto.create && mix ecto.load
