#!/bin/sh

# script/heroku-compile-assets: The asset compilation script called by the Heroku Phoenix Static buildpack.

yarn run deploy
cd $phoenix_dir
mix "${phoenix_ex}.digest"

if mix help "${phoenix_ex}.digest.clean" 1>/dev/null 2>&1; then
  mix "${phoenix_ex}.digest.clean"
fi
