defmodule Bridge.Signup do
  @moduledoc """
  This is a virtual model whose form changeset is designed to be bound to the
  new pod sign up form.
  """

  import Ecto.Changeset
  alias Ecto.Multi

  alias Bridge.Repo
  alias Bridge.Pod
  alias Bridge.User

  @types %{
    pod_name: :string,
    username: :string,
    email: :string,
    password: :string,
    time_zone: :string,
    slug: :string
  }

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def form_changeset(struct, params \\ %{}) do
    # TODO: beef up validations
    #
    # - Validate uniqueness of email
    # - Validate uniqueness of username
    # - Validate time zone
    # - Gracefully handle DB-level uniqueness violations?
    {struct, @types}
    |> cast(params, Map.keys(@types))
    |> validate_required([:pod_name, :username, :email, :password])
    |> validate_length(:pod_name, min: 1, max: 255)
    |> validate_length(:email, min: 1, max: 254)
    |> validate_length(:username, min: 3, max: 20)
    |> validate_length(:password, min: 6)
    |> validate_format(:username, User.username_format, message: "must be lowercase and alphanumeric")
    |> validate_format(:email, User.email_format, message: "is invalid")
    |> put_autogenerated_slug
  end

  @doc """
  Builds an Ecto.Multi operation that will take a changeset and persist the
  new pod and user to the database when passed to `Repo.transaction`.
  """
  def transaction(changeset) do
    pod_changeset = Pod.signup_changeset(%Pod{}, pod_params(changeset))
    user_changeset = User.signup_changeset(%User{}, user_params(changeset))

    Multi.new
    |> Multi.insert(:pod, pod_changeset)
    |> Multi.run(:user, fn %{pod: pod} ->
      user_changeset
      |> put_change(:pod_id, pod.id)
      |> Repo.insert
    end)
  end

  defp pod_params(changeset) do
    %{pod_name: name, slug: slug} = changeset.changes
    %{name: name, slug: slug}
  end

  defp user_params(changeset) do
    Map.take(changeset.changes, [:username, :email, :password, :time_zone])
  end

  defp put_autogenerated_slug(changeset) do
    case changeset do
      %Ecto.Changeset{changes: %{pod_name: name}} ->
        put_change(changeset, :slug, generate_slug(name))
      _ ->
        changeset
    end
  end

  # TODO: refine this a bit more?
  defp generate_slug(name) do
    name
    |> String.downcase
    |> String.replace(~r/[^(A-Za-z0-9|\-)]/, "-") # replace disallowed with -
    |> String.replace(~r/\--+/, "-") # remove duplicate dashes
    |> String.trim("-") # trim leading and trailing dashes
    |> String.slice(0..20) # truncate to 20 chars
  end
end
